# Generated by Django 4.2.7 on 2024-10-27 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 22, 51, 3, 879083, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
