# Generated by Django 4.2.7 on 2025-01-16 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_calculation_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 8, 6, 54, 212242, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
