# Generated by Django 4.2.7 on 2025-01-16 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_calculation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 8, 7, 21, 727102, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
